package com.mycompany.ecommerce.repositories;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.mycompany.ecommerce.domain.Client;
import com.mycompany.ecommerce.domain.PurchaseOrder;

@Repository
public interface PurchaseOrderRepository extends JpaRepository<PurchaseOrder, Integer>{

	// ---------- Automatic querie generated by Spring
	@Transactional(readOnly = true)
	Page<PurchaseOrder> findByClient(Client client, Pageable pageable);
	
}
